### PR TITLE
Feature/update spring

### PR DESCRIPTION
**Pull request by Dovchiproeng**
This PR aims to upgrade all spring boot version to 2.0.3.RELEASE and spring cloud to FINCHLEY.RELEASE

During upgrade :
- I fixed unit test due to the upgrade of spring boot
- also spring data jpa deprecate findOne to findById which return optional which enforce us to check null
- use @DataMongoTest to test DAO layer which reduce testing time by avoid starting the whole spring boot application

Also, I plan to centralize the spring boot and spring cloud version in the parent pom file, but think of loose coupling principal of microservice, each microservices might have different version of spring. So I didn't do that, @sqshq let me know how you think about the spring version centralization in pom parent.

If possible could you please create a feature branch **feature/update-spring**, so I could change to merge to that branch first. Then we can spend times to verify everything on it before we tag and merge to master.

### CODE REVIEW

**Comment by Dovchiproeng** [comment]
All function work as normal, it runs on docker local. Thanks, @xbitlabs for all the feedback

**Comment by sqshq** [comment]
Hi @Dovchiproeng. Yes, everything looks good. Thank you very much for the contribution! I've checked functionality as well, so I don't see a reason to merge it into feature branch before merge into master.

Regarding Spring version centralization - I don't think it is a bad idea for this project, I'm ok with such change - you can create a PR if you'd like

**Comment by Dovchiproeng** [comment]
@sqshq thanks for your verification. I think it would be good that we could tag the previous master branch as spirng.version.1 to remain the record.

**Comment by sqshq** [comment]
Yep, makes sense. Did that: https://github.com/sqshq/PiggyMetrics/tags

**Comment by Dovchiproeng** [comment]
@sqshq thanks, one more request, could you please delete branch feature/update-spring?

**Comment by sqshq** [comment]
@Dovchiproeng sure, done

**Pull request merged**
